[FEATURE] #4 Fetch text/image for Card component
minh197/WeBlog pull request #17
Opened 2024-03-17 21:49 UTC by minh197

## Addressing: https://github.com/minh197/WeBlog/issues/4
## How to test: Locally
1. Create a new `.env` file in the `client` folder
2. `REACT_APP_API_KEY=7fbeff6f514f42f59fb852e44770e829`
You can get a new API key from the `https://newsapi.org/` as well (or you can use my API key to test this ticket)
3. Pull the change from my ticket
4. Run `npm start`
5. See that we are able to fetch the data from News API rendered it correctly to our card components
<img width="1485" alt="Screenshot 2024-03-24 at 2 27 44 PM" src="https://github.com/minh197/WeBlog/assets/61608148/354183c3-0f60-4b08-a238-ef1fb9070923">

2024-03-24 19:28 UTC, minh197 commented
Pr is ready to review @Moethantko @naod1993

2024-03-31 00:15 UTC, Moethantko requested changes

2024-03-31 00:15 UTC, Moethantko commented on client/src/App.js
> +      <Card cardInfo={cardInfo}/>
```suggestion
      <Route path="/" element={<Cards />} />
```

I think we don't really want logic in `App.tsx`. And, we want to display all the Cards in the home route ("/"). Cards component should have a child component `Card`.

2024-03-31 00:15 UTC, Moethantko commented on client/src/components/Card/Card.jsx
> +      {cardInfo.map((info, index) => {
The logic for fetching `cardInfo` should be in this component, and this component should be renamed `Cards.jsx` in my opinion.

2024-03-31 00:15 UTC, Moethantko commented on client/src/components/Card/Card.jsx
> +          <div key={index} className="card">
I think this entire `div` should be in a seperate component, `Card.jsx`.

2024-03-31 00:19 UTC, Moethantko commented on client/src/App.js
> +    const fetchCardInfo = async() => {
```suggestion
    (async() => {
      try {
        const response = await axios.get(`https://newsapi.org/v2/top-headlines?country=us&category=science&apiKey=${apiKey}`)
        setCardInfo(response.data.articles);
      } catch (error) {
        console.error("Error fetching news", error);
      }
    })()
```

Just a thought.

2024-04-07 23:31 UTC, Moethantko requested changes
Just a question about the `useEffect` in `App.tsx`. Other than that, everything looks good!

2024-04-07 23:31 UTC, Moethantko commented on client/src/App.js
>    useEffect(() => {
I also meant that this entire useEffect can be in `Cards.jsx`. Why do we need to pass `cardInfo` to `Cards.jsx` if we could fetch it in the component itself? I'm not sure if you have another reason for having API fetching code in `App.tsx.` But, I'd do it in the component.

2024-04-07 23:36 UTC, minh197 commented on client/src/App.js
>    useEffect(() => {
Adjusted accordingly. Pls review again!

2024-04-07 23:39 UTC, Moethantko approved these changes
Looks good!

2024-04-07 23:39 UTC, merged