[FEATURE] Build the card component
minh197/WeBlog pull request #8
Opened 2024-03-13 04:19 UTC by minh197

## Addressing issue: https://github.com/minh197/WeBlog/issues/2

2024-03-14 04:05 UTC, Moethantko commented on client/package.json
> +    "bootstrap": "^5.3.3",
Is bootstrap package pre-requisite to use react-boostrap?

2024-03-14 16:07 UTC, minh197 commented on client/package.json
> +    "bootstrap": "^5.3.3",
I think so. The script was installed when I installed React Bootstrap

2024-03-16 15:33 UTC, minh197 commented
@Moethantko PR is ready to review

2024-03-16 21:53 UTC, Moethantko requested changes

2024-03-16 21:53 UTC, Moethantko commented on client/src/App.js
> +      <div className="card-list">
Can we put the stylings in respective components?

2024-03-16 21:53 UTC, Moethantko commented on client/src/components/Card.jsx
> +      <div className='card'>
I thought we discussed having an image placeholder in a card so that we could have retrieve images from a fake api and display those in the card.

2024-03-16 21:53 UTC, Moethantko commented on client/src/App.css
> +.card-list {
I don't think we want component-specific stylings in App.css which should only be a place for common styles.

2024-03-17 17:26 UTC, minh197 commented on client/src/App.js
> +      <div className="card-list">
yup! let me do that!

2024-03-17 17:42 UTC, minh197 commented on client/src/components/Card.jsx
> +      <div className='card'>
I put a sample image tag in the recent push to see how the card displays with an image. Let me know what you think. Thanks.

2024-03-17 19:04 UTC, Moethantko approved these changes
LGTM!

2024-03-17 19:04 UTC, merged